version: '3.3'

services:
  news-service:
    build: ./news-service/.
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILE: redis
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: clevertec
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
      CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - postgres
      - cache
      - config-server

  postgres:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clevertec
    networks:
      - postgres-network
    restart: unless-stopped

  config-server:
    build: ./config-server/.
    ports:
      - "8888:8888"
    networks:
      - postgres-network

  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - postgres-network

networks:
  postgres-network:
