version: '3.3'

services:
  news-api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: medievil/docker-springboot-postgres:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: clevertec
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - postgres
      - cache

  postgres:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clevertec
    networks:
      - postgres-network
    restart: unless-stopped

  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - postgres-network

networks:
  postgres-network:
