spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clevertec
    username: postgres
    password: 5310Defender
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
  liquibase:
    enabled: true
