INSERT INTO news VALUES (1, '2020-06-12 23:26:33', 'The secret of the presidential cue card', 'Los Angeles Times reporter Courtney Subramanian’s question did turn out to be on a basically similar issue to the one predicted on Biden’s card – about an apparent conflict between US efforts to slow semiconductor manufacturing in China and the trading interests of its allies. But the query did not exactly match the one Biden was apparently expecting and the LA Times said in a statement that Subramanian did not submit her question to the press office in advance, though she had been in regular contact with White House aides seeking information for her reporting.', 'Polli');
INSERT INTO news VALUES (2, '2020-07-06 02:18:37', 'Discord leaker. Catch up on the new allegations', 'CNN — It’s been two weeks since 21-year-old Jack Teixeira was arrested in shorts in front of his mother’s house, accused of leaking a trove of classified documents over a period of months to a closed online community on Discord, a social media platform popular with video gamers.', 'Ignavia');
INSERT INTO news VALUES (3, '2022-09-22 04:18:35', 'States are moving in polar opposite directions on guns', 'CNN - With almost all gun legislation a nonstarter on a divided Capitol Hill, states are charting wildly divergent paths. Some states are doing everything they can to restrict access to certain weapons. Others are doing everything they can to make guns as accessible as possible without much government oversight. On the restriction side, Washington on Tuesday became the 10th state to impose an assault-weapons ban, signaling new movement among states to step in where the federal government has failed. The national assault-weapons ban, which was in place for 10 years, lapsed in 2004.', 'Polli');
INSERT INTO news VALUES (4, '2021-11-03 06:29:30', 'Election 2024. A consequential rematch of serial candidates', 'CNN — This could be the most consequential rematch in US history – a president who portrays himself as the champion of democracy against a former president who routinely rejects election results. Anyone fearing Donald Trump’s return and those who reject Joe Biden’s victory could agree that nothing less than the future of the republic is at stake if Biden and Trump are on the ballot in 2024. Biden explicitly made that case in his announcement video on Tuesday, saying “we still are” in a “battle for the soul of America.”', 'Ignavia');
INSERT INTO news VALUES (5, '2021-11-06 06:40:22', 'McCarthy’s victory on debt ceiling vote may be short-lived', 'CNN — Speaker Kevin McCarthy passed his toughest test yet by buying off holdout Republicans and squeezing a bill with huge spending cuts through the House on Wednesday. But the price of proving his authority with a radical GOP conference was pushing the nation closer to a debt default cliff edge in an increasingly alarming showdown with President Joe Biden. The bill, which raises the debt ceiling for a year in return for spending cuts, was designed to hike pressure on Biden, who is refusing to accept Republican conditions that would effectively gut his domestic agenda. Unless the debt ceiling is lifted by the summer, the economy could crash.', 'Sycosis');
INSERT INTO news VALUES (6, '2020-03-10 06:06:28', 'Billionaire GOP donor says DeSantis won''t return his calls', 'John Catsimatidis, the billionaire CEO of the Gristedes supermarket chain who donated to Donald Trump''s 2020 re-election campaign, says that Florida Gov. Ron DeSantis isn''t returning his calls despite DeSantis eying a 2024 presidential run.', 'Polli');
INSERT INTO news VALUES (7, '2022-06-26 08:23:00', 'We are already in the food fight portion of the GOP primary', 'CNN — The 2024 Republican presidential primary is not fully underway as yet and already we are in the food fight phase. A super PAC supporting former President Donald Trump tried to smear Florida Gov. Ron DeSantis with pudding, seizing on a report, which the governor denies, about his eating habits to make a point about Social Security and Medicare. The ad itself is gross. And it drew a super PAC supporting DeSantis off the sidelines to air an ad of its own wondering why Trump was going after the Florida governor.', 'Cellular');
INSERT INTO news VALUES (8, '2021-07-12 06:52:31', 'Sexual assaults in the US military increased by 1% last year', 'CNN — The US military saw a 1% increase in sexual assaults last year, according to the Pentagon’s latest annual report. There were 7,378 reports of sexual assault against service members in 2022, according to the Fiscal Year 2022 Annual Report on Sexual Assault in the Military, released on Thursday. That is up from 7,260 reports of assault in 2021. All of the services aside from the Army saw an increase in reports from last year, officials said during a briefing on the report on Thursday. the Navy, Marine Corps, and Air Force saw a 9%, 3.6%, and 13% increase in reports, respectively. The Army, meanwhile, saw a 9% decrease.', 'Cellular');
INSERT INTO news VALUES (9, '2021-02-28 06:25:40', 'US Army renames Fort Lee after 2 pioneering Black Army officers', 'CNN  — The US Army renamed Virginia’s Fort Lee military base Thursday in honor of two Black service members, following a branch-wide push to rename bases named after Confederate leaders. The base will be “redesignated” as Fort Gregg-Adams after Lt. Gen. Arthur Gregg and Lt. Col. Charity Adams, the Army announced on Twitter. It had been named after Gen. Robert E. Lee, who led Confederate forces in the American Civil War. “Both Soldiers excelled in the field of sustainment and made significant contributions to USArmy history, the Army said in a tweet. We’re proud to honor the courage, sacrifice, and diversity of these distinguished Soldiers and also our civilians.', 'Sycosis');
INSERT INTO news VALUES (10, '2021-05-22 13:55:15', 'Ukraine war. Russia launches second pre-dawn missile attack in three days', 'Russia has launched a series of missiles at Ukrainian cities in the second pre-dawn attack in three days. Pavlohrad, a logistics hub near the central city of Dnipro, was hit ahead of a much-anticipated counter-offensive by Ukraine. The strike sparked a major fire, destroyed dozens of houses, and wounded 34 people. Hours later, the air raid alert sounded across the country, with the capital Kyiv among the targets. Across the country, the Ukrainian army said it shot down 15 of the 18 cruise missiles that had been fired.', 'Sycosis');

SELECT SETVAL('news_id_seq', (SELECT MAX(id) FROM news));

INSERT INTO comments VALUES (1, '2022-03-17 14:36:55', 'Nice news', 'Cellular', 1);
INSERT INTO comments VALUES (2, '2023-03-15 20:06:47', 'Don’t even compare our situations with each other, my problems are a lot more complicated and awful.', 'Polli', 2);
INSERT INTO comments VALUES (3, '2021-08-18 21:16:16', 'I hate it when people use emoji’s instead of answers, emoji’s make any conversation unserious.', 'Norman', 3);
INSERT INTO comments VALUES (4, '2021-03-09 08:31:28', 'Zebra, why zebra has such a weird set of colors???', 'Curlicue', 4);
INSERT INTO comments VALUES (5, '2022-05-22 13:40:35', 'I value information which you provide and always find your tips super useful.', 'Ignavia',1 );
INSERT INTO comments VALUES (6, '2022-02-23 16:51:54', 'I have different priorities, it is okay you know, we don’t have to be all the same mate…', 'Sycosis', 3);
INSERT INTO comments VALUES (7, '2021-06-19 09:33:35', 'I told you that new economy crisis is near, did you hear what happened to Deutsche Bank? They fired thousands of workers, it is a sign.', 'Conundrum', 4);
INSERT INTO comments VALUES (8, '2021-08-29 15:47:57', 'I’m so happy, I took couple of painting lessons and I already feel like little Michelangelo.', 'Curlicue', 2);
INSERT INTO comments VALUES (9, '2020-10-08 12:09:49', 'Truth is out there, boy I loved to watch X-files in my childhood, one of my favorites.', 'Jentacular', 5);
INSERT INTO comments VALUES (10, '2020-10-27 17:01:36', 'Weeb memes are so funny, well done Japan, you are good at creating memes.', 'LimanYawp', 6);
INSERT INTO comments VALUES (11, '2021-03-09 08:31:28', 'I double-checked my papers and I have no idea what is wrong with it, can you specify your issue please?', 'Cellular', 7);
INSERT INTO comments VALUES (12, '2023-04-27 11:21:19', 'Handy blog, I always come here when I want to find some solution or guide.', 'Ignavia', 7);
INSERT INTO comments VALUES (13, '2023-04-07 10:12:22', 'Hey guys, so I just joined your thread and I want to say that YOU GUYS ARE AWESOME!!!', 'Scribable', 2);
INSERT INTO comments VALUES (14, '2020-05-11 18:34:15', 'Not now, in couple of years maybe, but not right now. Also let me know when release of your service is.', 'GantornGasbag', 6);
INSERT INTO comments VALUES (15, '2022-02-27 11:18:19', 'Fantastic mood I’m having right now, Friday + vacation and salary D', 'Sycosis', 8);
INSERT INTO comments VALUES (16, '2020-09-03 14:00:00', 'What about other issues? This one is resolved okay, but other issues are also crucial.', 'Conundrum', 2);
INSERT INTO comments VALUES (17, '2021-06-29 20:13:28', 'Doing my maximum, it will take some time, but I think I will be able to fix this issue, just give me some time.', 'Curlicue', 9);
INSERT INTO comments VALUES (18, '2020-04-11 21:08:04', 'What is wrong with people? They seem to be very aggressive and they can’t tolerate different point of view.', 'Jentacular', 9);
INSERT INTO comments VALUES (19, '2022-09-13 07:39:13', 'How about we wait for him first, listen to his advice and make decision afterwards? Sounds good?', 'MenexVerily', 1);
INSERT INTO comments VALUES (20, '2022-09-06 10:42:11', 'I just can''t stop playing puzzle games, no matter how many times I try it never gets boring.', 'Boleromorph511', 9);

SELECT SETVAL('comments_id_seq', (SELECT MAX(id) FROM comments));